name = "ThickNumbers"
uuid = "b57aa878-5b76-4266-befc-f8e007760995"
authors = ["Tim Holy <tim.holy@gmail.com> and contributors"]
version = "1.0.0"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[weakdeps]
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"

[extensions]
ThickNumbersForwardDiffExt = "ForwardDiff"
ThickNumbersMooncakeExt = "Mooncake"

[compat]
DifferentiationInterface = "0.6"
ForwardDiff = "0.10, 1"
LinearAlgebra = "1"
Mooncake = "0.4"
julia = "1.9"

[extras]
DifferentiationInterface = "a0c0ee7d-e4b9-4e03-894e-1c5f64a51d63"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
Mooncake = "da2b9cff-9c12-43a0-ae48-6db2b0edb7d6"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DifferentiationInterface", "ForwardDiff", "Mooncake", "Test"]
